//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSer.ServiceActividades {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceActividades.WebServiceTestSoap")]
    public interface WebServiceTestSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Descr del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stInserAct", ReplyAction="*")]
        WebAppSer.ServiceActividades.stInserActResponse stInserAct(WebAppSer.ServiceActividades.stInserActRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/stInserAct", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppSer.ServiceActividades.stInserActResponse> stInserActAsync(WebAppSer.ServiceActividades.stInserActRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class stInserActRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="stInserAct", Namespace="http://tempuri.org/", Order=0)]
        public WebAppSer.ServiceActividades.stInserActRequestBody Body;
        
        public stInserActRequest() {
        }
        
        public stInserActRequest(WebAppSer.ServiceActividades.stInserActRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class stInserActRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Descr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email;
        
        public stInserActRequestBody() {
        }
        
        public stInserActRequestBody(string Descr, string Email) {
            this.Descr = Descr;
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class stInserActResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="stInserActResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebAppSer.ServiceActividades.stInserActResponseBody Body;
        
        public stInserActResponse() {
        }
        
        public stInserActResponse(WebAppSer.ServiceActividades.stInserActResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class stInserActResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stInserActResult;
        
        public stInserActResponseBody() {
        }
        
        public stInserActResponseBody(string stInserActResult) {
            this.stInserActResult = stInserActResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTestSoapChannel : WebAppSer.ServiceActividades.WebServiceTestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTestSoapClient : System.ServiceModel.ClientBase<WebAppSer.ServiceActividades.WebServiceTestSoap>, WebAppSer.ServiceActividades.WebServiceTestSoap {
        
        public WebServiceTestSoapClient() {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppSer.ServiceActividades.stInserActResponse WebAppSer.ServiceActividades.WebServiceTestSoap.stInserAct(WebAppSer.ServiceActividades.stInserActRequest request) {
            return base.Channel.stInserAct(request);
        }
        
        public string stInserAct(string Descr, string Email) {
            WebAppSer.ServiceActividades.stInserActRequest inValue = new WebAppSer.ServiceActividades.stInserActRequest();
            inValue.Body = new WebAppSer.ServiceActividades.stInserActRequestBody();
            inValue.Body.Descr = Descr;
            inValue.Body.Email = Email;
            WebAppSer.ServiceActividades.stInserActResponse retVal = ((WebAppSer.ServiceActividades.WebServiceTestSoap)(this)).stInserAct(inValue);
            return retVal.Body.stInserActResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppSer.ServiceActividades.stInserActResponse> WebAppSer.ServiceActividades.WebServiceTestSoap.stInserActAsync(WebAppSer.ServiceActividades.stInserActRequest request) {
            return base.Channel.stInserActAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppSer.ServiceActividades.stInserActResponse> stInserActAsync(string Descr, string Email) {
            WebAppSer.ServiceActividades.stInserActRequest inValue = new WebAppSer.ServiceActividades.stInserActRequest();
            inValue.Body = new WebAppSer.ServiceActividades.stInserActRequestBody();
            inValue.Body.Descr = Descr;
            inValue.Body.Email = Email;
            return ((WebAppSer.ServiceActividades.WebServiceTestSoap)(this)).stInserActAsync(inValue);
        }
    }
}
